version: '3.7'

services:
    # MySQL
    db:
        image: mysql:5.7
        container_name: codecamp-mainproject-db
        env_file: .env
        environment:
            TZ: Asia/Seoul
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        ports:
            - 3306:3306
        restart: always

    # NestJS
    api:
        # Dockerfile 설정
        build:
            # Dockerfile의 위치
            context: .

        container_name: codecamp-mainproject-api

        # Container Port 연결
        #   - host:container
        ports:
            - 3000:3000

        # Volume Mount
        #   - host:container
        volumes:
            - ./src:/app/src

            - ./test:/app/test

            - ./package.json:/app/package.json
            - ./yarn.lock:/app/yarn.lock
            - ./.env:/app/.env

            - /app/node_modules

        # 환경 변수 설정
        env_file: .env

        # 재시작 설정
        restart: always
