version: '3.7'

services:
    # MySQL
    db:
        image: mysql:5.7
        container_name: codecamp-mainproject-db
        env_file: ./backend/.env
        volumes:
            - ./db/conf.d:/etc/mysql/conf.d
        ports:
            - 3306:3306
        restart: always

    # NestJS
    api:
        # Dockerfile 설정
        build:
            # Dockerfile의 위치
            context: ./backend

        container_name: codecamp-mainproject-api

        # Container Port 연결
        #   - host:container
        ports:
            - 3000:3000

        # Volume Mount
        #   - host:container
        volumes:
            - ./backend/src:/app/src
            - ./backend/test:/app/test
            - ./backend/dist:/app/dist

            - ./backend/package.json:/app/package.json
            - ./backend/yarn.lock:/app/yarn.lock
            - ./backend/tsconfig.build.json:/app/tsconfig.build.json
            - ./backend/tsconfig.json:/app/tsconfig.json
            - ./backend/.env:/app/.env

            - ./backend/node_modules:/app/node_modules

        # 환경 변수 설정
        env_file: ./backend/.env

        # 재시작 설정
        restart: always

    # # Admin
    # api-admin:
    #     # Dockerfile 설정
    #     build:
    #         # Dockerfile의 위치
    #         context: ./admin
    #         dockerfile: Dockerfile

    #     container_name: codecamp-mainproject-api-admin

    #     # Container Port 연결
    #     #   - host:container
    #     ports:
    #         - 3002:3002

    #     # Volume Mount
    #     #   - host:container
    #     volumes:
    #         - ./admin/src:/app/src
    #         - ./admin/test:/app/test
    #         - ./admin/build:/app/build

    #         - ./admin/package.json:/app/package.json
    #         - ./admin/yarn.lock:/app/yarn.lock
    #         - ./admin/tsconfig.build.json:/app/tsconfig.build.json
    #         - ./admin/tsconfig.json:/app/tsconfig.json
    #         - ./admin/.babelrc:/app/.babelrc
    #         - ./admin/webpack.config.js:/app/webpack.config.js
    #         - ./admin/.env:/app/.env

    #         - ./admin/node_modules:/app/node_modules

    #     # 환경 변수 설정
    #     env_file: ./admin/.env

    #     # 재시작 설정
    #     restart: always
