version: '3.7'

services:
    # MySQL
    db:
        image: mysql:5.7
        container_name: codecamp-mainproject-db
        env_file: ./envs/.env.dev
        volumes:
            - ./db/conf.d:/etc/mysql/conf.d
        ports:
            - 3306:3306
        restart: always

    # NestJS
    api:
        # Dockerfile 설정
        build:
            # Dockerfile의 위치
            context: ./backend

        container_name: codecamp-mainproject-api

        # Container Port 연결
        #   - host:container
        ports:
            - 3000:3000

        # Volume Mount
        #   - host:container
        volumes:
            - ./backend/src:/app/src
            - ./backend/test:/app/test
            - ./backend/dist:/app/dist

            - ./backend/package.json:/app/package.json
            - ./backend/yarn.lock:/app/yarn.lock
            - ./backend/tsconfig.build.json:/app/tsconfig.build.json
            - ./backend/tsconfig.json:/app/tsconfig.json
            - ./envs/.env.dev:/app/.env

            - ./backend/node_modules:/app/node_modules

        # 환경 변수 설정
        env_file: ./envs/.env.dev

        # 재시작 설정
        restart: always

    # Admin
    api-admin:
        # Dockerfile 설정
        build:
            # Dockerfile의 위치
            context: ./admin
            dockerfile: Dockerfile

        container_name: codecamp-mainproject-api-admin

        # Container Port 연결
        #   - host:container
        ports:
            - 3001:3001

        # Volume Mount
        #   - host:container
        volumes:
            - ./admin/src:/app/src
            - ./admin/test:/app/test
            - ./admin/dist:/app/dist

            - ./admin/package.json:/app/package.json
            - ./admin/yarn.lock:/app/yarn.lock
            - ./admin/tsconfig.build.json:/app/tsconfig.build.json
            - ./admin/tsconfig.json:/app/tsconfig.json
            - ./envs/.env.dev:/app/.env

            - ./admin/node_modules:/app/node_modules

        # 환경 변수 설정
        env_file: ./envs/.env.dev

        # 재시작 설정
        restart: always
