version: '3.7'

services:
    # MySQL
    db:
        image: mysql:5.7
        container_name: codecamp-mainproject-db
        env_file: .env
        volumes:
            - ./db/conf.d:/etc/mysql/conf.d
        ports:
            - 3306:3306
        restart: always

    # NestJS
    api:
        # Dockerfile 설정
        build:
            # Dockerfile의 위치
            context: .

        container_name: codecamp-mainproject-api

        # Container Port 연결
        #   - host:container
        ports:
            - 3000:3000

        # Volume Mount
        #   - host:container
        volumes:
            - ./src:/app/src
            - ./test:/app/test
            - ./dist:/app/dist

            - ./package.json:/app/package.json
            - ./yarn.lock:/app/yarn.lock
            - ./tsconfig.build.json:/app/tsconfig.build.json
            - ./tsconfig.json:/app/tsconfig.json
            - ./.env:/app/.env

            - ./node_modules:/app/node_modules

        # 환경 변수 설정
        env_file: .env

        # 재시작 설정
        restart: always

    # NestJS Admin
    api-admin:
        # Dockerfile 설정
        build:
            # Dockerfile의 위치
            context: .
            dockerfile: Dockerfile.admin

        container_name: codecamp-mainproject-api-admin

        # Container Port 연결
        #   - host:container
        ports:
            - 3001:3001

        # Volume Mount
        #   - host:container
        volumes:
            - ./src:/app/src
            - ./test:/app/test
            - ./dist:/app/dist

            - ./package.json:/app/package.json
            - ./yarn.lock:/app/yarn.lock
            - ./tsconfig.build.json:/app/tsconfig.build.json
            - ./tsconfig.json:/app/tsconfig.json
            - ./.env:/app/.env

            - ./node_modules:/app/node_modules

        # 환경 변수 설정
        env_file: .env

        # 재시작 설정
        restart: always
