version: "3.7"

services:
    # Database
    my-db: 
        build:
            context: .
            dockerfile: Dockerfile.mongo
        ports:
            - 27017:27017

    # Express
    my-express:
        # Dockerfile 설정
        build:
            # Dockerfile의 위치
            context: . 
            # Dockerfile의 이름
            dockerfile: Dockerfile.express
        
        # Container Port 연결
        #   - host:container
        ports:
            - 3000:3000